<?php

declare(strict_types=1);

return [
    'groups' => [
        'guest' => [
            'legal.*',
            'auth.phone',
            'auth.phone.store',
            'auth.whatsapp.wait',
            'locale.update',
            'login',
            'logout',
            'password.*',
            'register',
            'verification.*',
        ],
        'app' => [
            'legal.*',
            'auth.phone',
            'auth.phone.store',
            'auth.whatsapp.wait',
            'locale.update',
            'home',
            'wallet',
            'wallet.history',
            'exchange',
            'exchange.orders.*',
            'withdraw',
            'withdraw.*',
            'kyc',
            'kyc.*',
            'profile.*',
            'logout',
        ],
        'admin' => [
            'admin.*',
            'auth.phone',
            'auth.phone.store',
            'auth.whatsapp.wait',
            'home',
            'logout',
            'locale.update',
            'login',
        ],
        'admin_security' => [
            'admin.account',
            'admin.dashboard',
            'admin.kyc.*',
            'admin.orders.*',
            'admin.withdrawals.*',
            'auth.phone',
            'auth.phone.store',
            'auth.whatsapp.wait',
            'logout',
            'locale.update',
            'login',
        ],
        'admin_exchange' => [
            'admin.account',
            'admin.orders.*',
            'auth.phone',
            'auth.phone.store',
            'auth.whatsapp.wait',
            'home',
            'logout',
            'locale.update',
            'login',
        ],
    ],
];
